CREATE TABLE guest_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_id UUID NOT NULL UNIQUE,
    display_name VARCHAR(32),
    created_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_guest_session_display_name CHECK (display_name IS NULL OR btrim(display_name) <> ''),
    CONSTRAINT chk_guest_session_last_seen CHECK (last_seen_at >= created_at)
);

CREATE TABLE lobby (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(6) NOT NULL UNIQUE,
    host_guest_id UUID NOT NULL REFERENCES guest_session (guest_id) ON DELETE NO ACTION,
    status VARCHAR(16) NOT NULL,
    max_players SMALLINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_lobby_code CHECK (code ~ '^[A-Z0-9]{6}$'),
    CONSTRAINT chk_lobby_status CHECK (status IN ('WAITING', 'IN_GAME', 'FINISHED', 'EXPIRED')),
    CONSTRAINT chk_lobby_max_players CHECK (max_players BETWEEN 2 AND 8),
    CONSTRAINT chk_lobby_expiry CHECK (expires_at > created_at)
);

CREATE TABLE participant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lobby_id BIGINT NOT NULL REFERENCES lobby (id) ON DELETE NO ACTION,
    guest_id UUID NOT NULL REFERENCES guest_session (guest_id) ON DELETE NO ACTION,
    display_name VARCHAR(32) NOT NULL,
    role VARCHAR(8) NOT NULL,
    joined_at TIMESTAMPTZ NOT NULL,
    connection_status VARCHAR(16) NOT NULL,
    CONSTRAINT uq_participant_lobby_guest UNIQUE (lobby_id, guest_id),
    CONSTRAINT chk_participant_display_name CHECK (btrim(display_name) <> ''),
    CONSTRAINT chk_participant_role CHECK (role IN ('HOST', 'PLAYER')),
    CONSTRAINT chk_participant_connection_status CHECK (connection_status IN ('CONNECTED', 'DISCONNECTED'))
);

CREATE TABLE game_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_type VARCHAR(32) NOT NULL,
    mode VARCHAR(16) NOT NULL,
    lobby_id BIGINT REFERENCES lobby (id) ON DELETE NO ACTION,
    status VARCHAR(16) NOT NULL,
    current_round SMALLINT NOT NULL,
    total_rounds SMALLINT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    CONSTRAINT chk_game_session_game_type CHECK (btrim(game_type) <> ''),
    CONSTRAINT chk_game_session_mode CHECK (mode IN ('SINGLE_PLAYER', 'MULTIPLAYER')),
    CONSTRAINT chk_game_session_lobby_mode CHECK (
        (mode = 'SINGLE_PLAYER' AND lobby_id IS NULL)
        OR (mode = 'MULTIPLAYER' AND lobby_id IS NOT NULL)
    ),
    CONSTRAINT chk_game_session_status CHECK (status IN ('IN_PROGRESS', 'FINISHED', 'CANCELLED')),
    CONSTRAINT chk_game_session_round CHECK (total_rounds > 0 AND current_round BETWEEN 1 AND total_rounds),
    CONSTRAINT chk_game_session_finished_at CHECK (
        (status = 'IN_PROGRESS' AND finished_at IS NULL)
        OR (status IN ('FINISHED', 'CANCELLED') AND finished_at >= started_at)
    )
);

CREATE TABLE round_submission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_session_id BIGINT NOT NULL REFERENCES game_session (id) ON DELETE NO ACTION,
    round_number SMALLINT NOT NULL,
    participant_id BIGINT REFERENCES participant (id) ON DELETE NO ACTION,
    target_color VARCHAR(7) NOT NULL,
    guessed_color VARCHAR(7) NOT NULL,
    score NUMERIC(12, 6) NOT NULL,
    color_distance NUMERIC(12, 6) NOT NULL,
    response_time_ms INTEGER NOT NULL,
    submitted_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_round_submission_once UNIQUE NULLS NOT DISTINCT (game_session_id, round_number, participant_id),
    CONSTRAINT chk_round_submission_round CHECK (round_number > 0),
    CONSTRAINT chk_round_submission_target_color CHECK (target_color ~ '^#[0-9A-Fa-f]{6}$'),
    CONSTRAINT chk_round_submission_guessed_color CHECK (guessed_color ~ '^#[0-9A-Fa-f]{6}$'),
    CONSTRAINT chk_round_submission_score CHECK (score BETWEEN 0 AND 10),
    CONSTRAINT chk_round_submission_distance CHECK (color_distance >= 0),
    CONSTRAINT chk_round_submission_response_time CHECK (response_time_ms >= 0)
);

CREATE UNIQUE INDEX uq_participant_lobby_display_name ON participant (lobby_id, lower(display_name));
CREATE UNIQUE INDEX uq_participant_lobby_host ON participant (lobby_id) WHERE role = 'HOST';
CREATE UNIQUE INDEX uq_game_session_active_lobby ON game_session (lobby_id)
    WHERE status = 'IN_PROGRESS' AND lobby_id IS NOT NULL;

CREATE INDEX idx_lobby_expires_at ON lobby (expires_at);
CREATE INDEX idx_participant_guest_id ON participant (guest_id);
CREATE INDEX idx_game_session_lobby_started_at ON game_session (lobby_id, started_at DESC);
